### PR TITLE
Prevent 'Access Denied' error in IE8 when used inside of an iFrame.

### PR DESCRIPTION
**Pull request by kyledetella**
This commit wraps the `document.selection.createRange();` call in a try/catch to prevent exceptions when library is used inside of an iFrame. If `createRange` does error out, the `inputSel.get` method will ultimately return `{ begin: 0, end: 0 }` as it always has.

### CODE REVIEW

**Comment by mrak** [comment]
:+1:

**Comment by jaridmargolin** [comment]
The library is dependent on `inptSel.get`. What is the result of returning `{ begin: 0, end: 0 }` on every call? I imagine the library would behave very oddly. Would the correct solution be to just disable formatter completely in these scenarios?

**Comment by kyledetella** [comment]
`{ begin: 0, end: 0 }` would only be returned in the case where `range = document.selection.createRange();` throws an error or `range.parentElement() !== el`.

If no error is raised (and `range` is defined), then the conditional [here](https://github.com/kyledetella/formatter.js/blob/master/src/inpt-sel.js#L36) would return the appropriate values.

**Comment by jaridmargolin** [comment]
I should have made myself more clear. What is the result of returning `{ begin: 0, end: 0 }` on every call made within an iframe in IE8? Hiding the error within a try catch does not solve the underlying problem that we are unable to get the correct selection. 

Should the error be silenced by wrapping it in a try catch as you have suggested, or should the library fail to initialize in such an environment?

**Comment by kyledetella** [comment]
I like the idea of having the library fail to initialize. However, the reason I chose to suppress the error was that IE8 only threw it once when formatter was initialized within an iFrame. Subsequent calls work just fine.

**Comment by heygambo** [comment]
@kyledetella pls send a pull request to https://github.com/nerdyglasses/cakepan

**Comment by kyledetella** [comment]
@nerdyglasses thanks for taking over this project! Its nice to see it being resurrected. I'll probably leave this issue/PR alone but good luck going forward.

**Pull request closed without merging**
