### PR TITLE
Minor typo fix: switch from "JQuery" to "jQuery"

### PR DESCRIPTION
**Pull request by EvanHahn**

### CODE REVIEW

**Comment by EvanHahn** [comment]
still not replying??

**Comment by jeffcarp** [comment]
pls respond

**Comment by jeffcarp** [comment]
get on with it

**Comment by EvanHahn** [comment]
do it

**Comment by ryanjpodonnell** [comment]
payattention2me

**Comment by pwizla** [comment]
giphy

**Comment by NickTomlin** [comment]
Wrap It Up

**Comment by crookedneighbor** [comment]
exit_360 gif png

**Comment by jeffcarp** [comment]
giphy

**Comment by ryanjpodonnell** [comment]
slack-imgs com

**Comment by ryanjpodonnell** [comment]
4772147-5896887189-giphy

**Comment by bbrodriges** [comment]
Do it!

**Comment by arturparkhisenko** [comment]
do it

**Comment by heygambo** [comment]
@EvanHahn this isn't even funny anymore. So many things and they just don't add collaborators or give this project to someone who actually cares. We should probably take the code, include all the PRs manually by hand and release it under a new name so that this drama can have an end.

**Comment by nerdyglasses** [comment]
@EvanHahn pls send a pull request to https://github.com/nerdyglasses/cakepan

**Comment by EvanHahn** [comment]
Goodnight, sweet prince.

**Pull request closed without merging**
