### PR TITLE
Fix CommonJS requires

### PR DESCRIPTION
**Pull request by marksteve**

### CODE REVIEW

**Comment by EvanHahn** [comment]
:+1: on this

**Comment by gajus** [comment]
@Jaymon, @jaridmargolin can this be merged?

Can you add me as a contributor to GitHub/ NPM to merge PRs such as this one?

**Comment by nerdyglasses** [comment]
@jaridmargolin @Jaymon would be great if you could merge a few of those. They are really good fixes!

**Comment by heygambo** [comment]
@marksteve pls send a pull request to https://github.com/nerdyglasses/cakepan

**Comment by Jaymon** [comment]
@nerdyglasses @gajus I just talked with @jaridmargolin, who has committed to adding some other maintainers to the repo by end of day today (December 6, 2016)

**Comment by heygambo** [comment]
Really? that would be awesome. I've just started copying over the changes. I've just pushed the commonjs changes to my repo.

**Comment by heygambo** [comment]
https://github.com/nerdyglasses/cakepan/pull/2

**Comment by heygambo** [comment]
@gajus why the thumbs down?

**Comment by gajus** [comment]
> @gajus why the thumbs down?

Please focus on supporting existing open-source effort (including liaising with project maintainers about making a release, becoming a contributor, etc) instead of forking a project and advertising it 7 hours later with a tagline:

> formatter.js is dead. CakePan for the win 🎂

**Comment by heygambo** [comment]
it was dead for years until a few hours ago. i just need those pull request to go through. i will delete my repo once i can work with the existing one

**Comment by heygambo** [comment]
and i gave it a new name so it doesnt have to be formatter2.js on npm (sorry i'm on the phone. can't edit my comment above)

**Comment by gajus** [comment]
1. Find the people with merge rights
1. Email them asking to become a contributor on the basis that you have raised PRs #, #, # and are actively relying on the project, and have an established track record in the open-source community.

Chances are the author will give you a contributor status.

Don't have reputation?

Look at the PRs by other authors. Find an author with a reputation. Offer to liaise on his behalf.

Simple.

**Comment by heygambo** [comment]
I feel you.

I just ask you to understand my point of view as well. there is a pr somewhere where people kept asking and there was no single sign of life.

That being said. I'm looking forward to using this project instead of mine obviously and love & respect goes to all of you.

**Comment by Jaymon** [comment]
@gajus @nerdyglasses I apologize for this situation, it's our fault. We moved away from this internally and we should've given more people commit access. 

I can be reached at jay@firstopinionapp.com if anyone needs to talk with me directly

**Comment by heygambo** [comment]
I have removed all my requests to send PRs to my repo and have changed the agrassive `formatter.js is dead` description. But I keep the repo for now so I can use it for a project until this one works.

**Comment by gajus** [comment]
Hi @Jaymon, thank you for the brilliant project and for taking time to follow up.

**Comment by jaridmargolin** [comment]
@nerdyglasses @gajus - Would like to make you both maintainers if you are interested. I think there would immense benefit in having some checks and balances before a PR is merged.

Thank you for your willingness to contribute to the project. As @Jaymon stated, it is our fault for not passing the torch earlier.

**Comment by gajus** [comment]
> @nerdyglasses @gajus - Would like to make you both contributors if you are interested. I think there would immense benefit in having some checks and balances before a PR is merged.

I am sorry, I am out of capacity at the moment to take on the torch. However, if you make me a contributor and someone pings me for a specific PR, I will be happy to review it.

**Comment by jaridmargolin** [comment]
@gajus building the bot to ping you on every PR right now :)

@EvanHahn, I'm not sure if braintree is making use of formatter, but I have seen several requests come in from braintree devs. Would anyone on your team like to come on as a maintainer?

Really would love to get multiple 👀 on PRs.

**Comment by gajus** [comment]
> @gajus building the bot to ping you on every PR right now :)

Funny enough, I am working on a project that does something very similar. :-)

**Comment by EvanHahn** [comment]
@jaridmargolin Braintree built [Restricted Input](https://github.com/braintree/restricted-input) which is a similar library. I don't think we'll be able to maintain this library, but thanks for the offer!

**Comment by heygambo** [comment]
@jaridmargolin sorry for the late response. I had a flu and didn't look here much.

I'm not sure I can promise anything at this time because my time is very limited.
I would let you know if anything changes with my situation.

**Comment by chrisdothtml** [comment]
Is there any reason this hasn't been merged? This is a pretty simple/straightforward PR; not sure what more review needs to happen to it

**Pull request closed without merging**
